name: test install

on:
  workflow_dispatch:  # manual runs
  push:
  pull_request:


jobs:
    test-macos:
        runs-on: macos-14
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4
            with:
              fetch-depth: 1

          - name: Install Miniconda
            uses: conda-incubator/setup-miniconda@v3
            with:
              auto-update-conda: true
              activate-environment: psi4_rado-tuto
              environment-file: install/psi4_rado-tuto.yaml


          - name: Run test script
            shell: bash -el {0}
            run: |
              cd minimal_script/run_lr
              psi4 *.psi4inp
