name: test install crossplat

on:
  workflow_dispatch:  # manual runs
  push:
  pull_request:


jobs:
    test-crossplat:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
          - name: Checkout repo
            uses: actions/checkout@v4
            with:
              fetch-depth: 1

          - name: Install Miniconda
            uses: conda-incubator/setup-miniconda@v3
            with:
              auto-update-conda: true
              activate-environment: psi4_rado-tuto
              environment-file: install/psi4_rado-tuto.yaml


          - name: Run test script
            shell: bash -el {0}
            run: |
              cd minimal_script/run_lr
              psi4 *.psi4inp
              cd -

          - name: Run test script
            shell: bash -el {0}
            run: |
              cd production_scripts/OPT_MP2_cc-pvtz_CO2.psi4inp
              psi4 *.psi4inp
              cd -

          - name: Run test script
            shell: bash -el {0}
            run: |
              cd production_scripts/PROPERTIES_PBE0_d-aug-cc-pvtz_CO2.psi4inp
              psi4 *.psi4inp
              cd -
